{
 "title": "eShopDashboar",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "traceId", "label": "traceId" }
  ]
 },
 "panels": [
  {
   "title": "Rate of basket update per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(basket_update_basket_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of items per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(basket_added_items_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate de errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(basket_update_basket_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web Service Update Basket Traces",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 16 },
   "targets": [
    { "operation": "BasketApi.Basket/UpdateBasket", "service": "WebService" }
   ]
  },
  {
   "title": "Selected trace ${traceId}",
   "type": "traces",
   "gridPos": { "h": 29, "w": 16, "x": 8, "y": 16 },
   "targets": [
    { "query": "${traceId}" }
   ]
  },
  {
   "title": "Web Service Get Basket Traces",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 30 },
   "targets": [
    { "operation": "BasketApi.Basket/GetBasket", "service": "WebService" }
   ]
  }
 ]
}